### ISSUE TITLE
Login through OpenID doesn't work

### ISSUE THREAD

**Issue by underdeadcmh** [C0D3D3V/Moodle-Downloader-2#106]
hey, due to usage of only openID login in our moodle system I see that it is not possible to log in :(
can something be done in such a case?
thanks

**Comment by C0D3D3V** [comment]
Can you send me the URL to your moodle? 
Some moodles with openID have the SSO plugins acticated, so you could try the `--sso` option on initialization.

**Comment by underdeadcmh** [comment]
it's moodle.ut.ee and --sso didn't work, thx for the fast reply tho

**Comment by C0D3D3V** [comment]
I have checked your Moodle instance, unfortunately it seems that your instance does not support the moodle app. You could contact an administrator of your instance and ask if they plan to enable the moodle app soon, you could suggest in your mail that the app is very helpful.

**Comment by C0D3D3V** [comment]
Oh oops I was wrong, I missed something. Wait, I can explain how to use the downloader.

**Comment by C0D3D3V** [comment]
Do you use https://moodle.ut.ee/auth/oidc/ or https://moodle.ut.ee/auth/est_id_card/login.php to log in?

**Comment by C0D3D3V** [comment]
Regardless, you can try this: https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Copy-a-token-from-the-Moodle-app

**Comment by underdeadcmh** [comment]
I am using the https://moodle.ut.ee/auth/oidc/
Tried getting token as described and even got it, decoded, failing at downloading account info with 404

**Comment by C0D3D3V** [comment]
I forgot that the method I explained in the wiki doesn't quite work on openid because chrome doesn't redirect to the app. I'll rewrite that so it works there too. 

Basically you just have to install the real Moodle Desktop app (https://download.moodle.org/desktop/) and do the same. On Arch Linux you can just install it from the AUR (moodledesktop-bin). The app uses Electron8 and correctly handles the redirection. Start the app in the terminal with `moodledesktop --debug` (on windows you have to replace `moodledesktop` with the path to the app if necessary). Alternatively you can use `env ELECTRON_ENV=development && moodledesktop` under Linux or `set ELECTRON_ENV=development && moodledesktop` under Windows.
Then open the debug consol with [Ctr + Shift + I] and activate the "Preserve log" checkbox in the Network tab. The keep going like in the wiki article described.

**Comment by C0D3D3V** [comment]
Which operating system do you use?

**Comment by underdeadcmh** [comment]
Gonna try the other method later, thanks.
It's kali with linux 5.9.0 kernel

**Comment by C0D3D3V** [comment]
Linux download Link for moodle dektop: https://download.moodle.org/desktop/linux/moodledesktop-linux-64-v380.tar.gz
It is a Appimage you can extract it like this: `./linux-x64.AppImage --appimage-extract`. It will create a directory with the name `squashfs-root. You can run moodledesktop from this directory. Alternatively you can use this PKGBUILD to install it: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=moodledesktop-bin.

Windows download link for moodle desktop: https://download.moodle.org/desktop/windows/moodledesktop-windows-v380.zip

**Comment by C0D3D3V** [comment]
I updated the wiki entry: https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Copy-a-token-from-the-Moodle-app

I hope this helps
