### ISSUE TITLE
The moodle app does not work, how do I still get a token?

### ISSUE THREAD

**Issue by Ectalite** [C0D3D3V/Moodle-Downloader-2#124]
Not really a bug but not an enhancement neither.

The IT in my school didn't enabled the moodle app web service. 
Would there be another to get the token ?

**Comment by C0D3D3V** [comment]
Since the moodle-dl only uses the interface of the moodle-app, there is little hope if the moodle-app does not work with your moodle.

If the Moodle app would work, you could try this procedure: https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Copy-a-token-from-the-Moodle-app

If the Moodle app doesn't work you could still check if you have online access to your security token, some Moodles allow this:
![grafik](https://user-images.githubusercontent.com/14315968/141321235-71b5de38-f4a7-4e64-8385-6fb26133122c.png)
![grafik](https://user-images.githubusercontent.com/14315968/141321314-41b0c30b-1119-4d40-a759-19c1a4b164cd.png)

If you have access, you can simply create [a configuration manually](https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Config.json ), and set the `token` there. The `privatetoken` is never accessible from the web, but it is not mandatory. 

Otherwise you only have to write a friendly email to the Moodle admin and ask if he could activate the [webservices](https://docs.moodle.org/311/en/Using_web_services#Enable_web_service_feature).

**Comment by C0D3D3V** [comment]
If you had success with the email you send to the admin, you could post the email here as a template for others :)

**Comment by Ectalite** [comment]
That's so sad, I only have access to this key:
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/31344054/141323527-94fea753-355c-463c-b944-4f28f61891f5.png">

I don't think you will be able to use this...

**Comment by Ectalite** [comment]
I asked the IT team and they deactivated it deliberately for security issues.

**Comment by C0D3D3V** [comment]
Too bad :/ I'm sorry to hear that.
Yes the RSS feed token can only be used on courses that have RSS enabled and only in combination with the RSS feed URL, but I haven't looked into it myself yet.

**Comment by C0D3D3V** [comment]
One wonders what kind of security problems they had with the activated web services O.o
