### ISSUE TITLE
Changelog file is not always public

### ISSUE THREAD

**Issue by marvinsxtr** [C0D3D3V/Moodle-Downloader-2#126]
https://github.com/C0D3D3V/Moodle-Downloader-2/blob/8abc87cef6e1f3ebbd87035c7f53f588c07701c3/moodle_dl/moodle_connector/request_helper.py#L211

This function fails when the requested URL is not publicly available, so it would be nice to add some default value or see if there is another way of getting the version. After choosing a random valid version, everything worked fine for me.

**Comment by C0D3D3V** [comment]
Did you get a `Connection error` or what type of error did you get?

In principle, the file should be available on every Moodle, because [it is integrated in the source code](https://github.com/moodle/moodle/blob/master/lib/upgrade.txt).
But yes of course would be good to have a fallback.

There are also other paths where a similar file should be found, e.g. /user/upgrade.txt; /mod/upgrade.txt; /webservice/upgrade.txt

But only with `/lib/upgrade.txt` you can be very sure that it contains the current version.

I would suggest that if the file is not found, that it is output accordingly that the version could not be detected and yet the automatic SSO procedure is offered.

**Comment by C0D3D3V** [comment]
If we would implement #12, we wouldn't need to query the version at all, because that would go in all functions.

**Comment by C0D3D3V** [comment]
this should fix it for now... To implement #112 is a lot more work ^^
