### ISSUE TITLE
Connection aborted issue in some cases. 

### ISSUE THREAD

**Issue by jonas-t-s** [C0D3D3V/Moodle-Downloader-2#131]
First of all: Thank you for your great project, I very like it!
## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

In some cases, where there are connection issues, those abort the synchronization, whilst I can guarantee that everything shall work as intended. 

## Steps to reproduce the issue
Run moodle-dl as cronjob every 5 mins and hope it happens. Unfortunately it happens randomly. Two days ago it occurred 3 times. Since I run it as a cronjob, I do not have a terminal output. 

  

[MoodleDownloader.log](https://github.com/C0D3D3V/Moodle-Downloader-2/files/7775755/MoodleDownloader.log)

## Technical details

 - OS: Manjaro Linux
 - Testing Branch

## Expected behavior

I believe this shall not happen. 

## Possible Fix

Maybe catch some exceptions during downloading and then retry and if it fails n times, throw it. like the following code:
```
i=0
while(True){
   try: 
        download()
   catch ConnectionError as e:
       i = i +1
       if i < 20: 
           continue  
       throw e
   break
}
```

**Comment by C0D3D3V** [comment]
Such a mechanism was actually implemented at the beginning of this project, but I have removed it, because you can run the moodle-dl again like you do anyway and it will download all the files that failed again. So it's not a problem if the download of a file fails, the next time you run the cron job the file will be downloaded again.

Also please provide your error log. 

It is very common that a moodle instance is not online the whole day, usually an instance goes into maintenance mode at unusual usage times and is unreachable.

**Comment by C0D3D3V** [comment]
By the way, running the cron-job every 15min. is actually also sufficient :) But since moodle doesn't have a rate limit built in anyway, 5 min. shouldn't be a problem either.

**Comment by jonas-t-s** [comment]
Thank you for your reply. I usually run it every 30 min, but due to testing I increased the frequency. 
And you're totally right, that I can and in my cronjob I just do it. I just wanted to let you know that this behavior exists. 

I didn't know that you decided to remove this feature(I've to admit, that I do not follow all commits), so this issue seems to be obsolete. 

Actually I've noticed, that even tough moodle doesn't have a rate limit, some webservers have one built in and some admins have configured it.

**Comment by C0D3D3V** [comment]
We could also add the feauture again, with an extra option to delay the downloader in case of network errors.

**Comment by C0D3D3V** [comment]
The feature was removed in b9903148714c704e38f46dd552cacce16a3c39c2

Setting `DownloadService.url_tries = 3` would try to download a file two more times.

**Comment by C0D3D3V** [comment]
But actually your error is not about downloading files. But the error occurred when calling the API. In fact, network errors are considered fatal with the API. So we could really think about building in something more robust, when calling the API. When downloading files, there are actually never problems, because the API usually blocks before, if something is wrong with the moodle server.

**Comment by jonas-t-s** [comment]
Hmm, that's interesting. 
I think that "building in something more robust, when calling the API" is a good idea. 
But as you've mentioned above, it isn't a huge problem, since we can restart and then it works.

**Comment by jonas-t-s** [comment]
If you don't mind, I would try to implement my kind of "possible fix". Is that fine for you, or do you think it should be solved different?

**Comment by C0D3D3V** [comment]
Gladly, I am open to any contribution :)
