### ISSUE TITLE
Cannot choose which courses to download

### ISSUE THREAD

**Issue by KtRNofficial** [C0D3D3V/Moodle-Downloader-2#142]
## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

In moodle-dl --config
During the first step I don't know how to move up and down between courses.
I can only use Space to disable the first course, however I cannot use - for example - the arrow keys to move the pointer up and down the list. This way, I would download even all those courses which I no longer visit - which is not useful for me.
I could not find any hints as to how to move up and down the list in the documentation.

Cheers, Ben
P.S. Grüße aus der RUB!
 

## Technical details

 - OS: Windows 11

## Expected behavior

I should be able to move up and down in the list using arrow keys

**Comment by C0D3D3V** [comment]
Hi,
Sorry for the long delay. Yes it was a known (windows only) bug, it was introduced by python-readchar in Januar. Because of that one could not use the arrow keys to navigate in the lists. I now added readchar to our repository and modified the failing part... Now we have full control over readchar and it should not fail anymore. Can you try out latest master and tell me if it works. If it works I will make a new Release.

Auch Grüße zurück ^^ Ich sollte wohl mal ein Discord Channel machen damit man sich austauschen kann ohne über github zu kommunizieren.

**Comment by C0D3D3V** [comment]
See https://github.com/Kamik423/cutie/issues/26

**Comment by KtRNofficial** [comment]
Thanks for replying though, no problem - in the mean time I manually removed the unwanted courses from the config.json so now the program works like a charm.

I'll try out the new master once I get back from campus today, though I'm quite new to Github and I'll have to find out how that works exactly - unless it just means grabbing the code from a .zip ^^

Klar, gern! Wie sollen wir das angehen? Grüße!

**Comment by C0D3D3V** [comment]
great, yes you can just download the zip, then unzip it and run in the directory `python moodle-dl --init` or any other argument :D

In principle I already tested it, but in a windows 10 VM.

**Comment by C0D3D3V** [comment]
I now also linked the discord server I created in the readme, if you need help testing the new changes, just write me there.

**Comment by C0D3D3V** [comment]
just fixed in the new release

**Comment by C0D3D3V** [comment]
@adriadam10 this should no longer happen, because I have removed the dependencies, and created our own version of cutie for moodle-dl.
Can you please create a new issue id you really think you have problems with it
