### ISSUE TITLE
On the latest build, additional configurations makes the program crash

### ISSUE THREAD

**Issue by federicotorrielli** [C0D3D3V/Moodle-Downloader-2#39]
![immagine](https://user-images.githubusercontent.com/31370059/84902457-21231700-b0ad-11ea-87c9-93d17c330461.png)

After the crash, running again the program makes it break.

How to reproduce: configure a new account on a fresh install, then, when the terminal asks you "Do you want to make additional configurations now?" press the arrow down to go to no.

Reproduction rate: 100% every time i configure a new account on a fresh install.

**Comment by C0D3D3V** [comment]
Why does windows always have to cause so many problems xD On linux the error does not happen. I'm going to test it under windwos.

**Comment by federicotorrielli** [comment]
I'm so sorry xD
And another thing, with the latest build if i don't make extra conf. and try downloading everything, it justs stops everytime and crashes the terminal at the 2nd/3th course check

**Comment by C0D3D3V** [comment]
Does the log say anything of significance?

**Comment by federicotorrielli** [comment]
Nothing at all. Do you want a video showing the problem?

**Comment by C0D3D3V** [comment]
If it's not too much trouble for you, that would be great.

**Comment by federicotorrielli** [comment]
Here's a video with a little voice explanation: https://streamable.com/pc6r81

Hope it helps.

**Comment by C0D3D3V** [comment]
Haha, yes that video is perfekt. 

I think the problem is, you might have activated downloading external files. 
Try to deactivate it first with setting `"download_linked_files": false,` 

If that helps, I would say it is a problem with youtube-dl that I use in the new release. 

I think it tries to run ffmpeg, but you may have not installed it. And I forgot to log the errors of youtube-dl. 

sorry for that... I didn't test that -.- I should take back the new release till i fixed that.

**Comment by federicotorrielli** [comment]
Same problem, even with the "download_linked_files": false, option on the config

**Comment by C0D3D3V** [comment]
Mh ok :( Did you try to wait longer?

**Comment by federicotorrielli** [comment]
I'll take a test rn, but I can tell you 2 things:
1) I have a fast fiber connection, even with a 1gb video, it should not be this hard to download, unless the resource is down!
2) This is the first time it does this on windows, but testing this on linux gives me no problem at all!

**Comment by C0D3D3V** [comment]
Ok then wait... I get to an windows machine in 10min...

**Comment by federicotorrielli** [comment]
1h passed, still there.

**Comment by C0D3D3V** [comment]
So I can not reproduce the error. But I could finally fix the ssl bug on windows :D :D 

I will try to add some more debuging prints. The threds are all reporting 0% at the crash so. On a normal crash it would report 100% :/   Mh so it only donlads a few files ~25mb and then all threads chrashs. maybe I have made a logical error that only triggers on special files. I will review my code tonight...

**Comment by federicotorrielli** [comment]
Nice, thanks, let me know!

**Comment by C0D3D3V** [comment]
Can you try do donwload only one course, that maybe has not such a special file ..

**Comment by C0D3D3V** [comment]
Just for the record, I can download all my courses on windows without any problem 1,2GB of files **without external files**! When I activate external files it sometimes hangs for a moment, but in itself it works, even without installing ffmpg itself.

**Comment by C0D3D3V** [comment]
And I've noticed a strange behavior with the download path on windows, maybe that's also a problem, is really exhausting to develop cross-platform.

**Comment by C0D3D3V** [comment]
With ffmpeg videos seem to be destroyed after downloading -.- oh man. I take back the release.

**Comment by C0D3D3V** [comment]
Does the old release work normal ?

**Comment by C0D3D3V** [comment]
By the way, I took a closer look at your picture from the first post. So in the code itself there is actually a little logic error which should never be a problem, I have no idea how you even get this error, because "keypress" can never be None.  But I still fix the logic error.

**Comment by C0D3D3V** [comment]
I made some fixes. Download should now work hopefully

**Comment by federicotorrielli** [comment]
The download still stops for me, even with only 1 course active.
I'm gonna try not downloading external video/audio files now and reach out to you.

**Comment by federicotorrielli** [comment]
Still stops, even with "download_linked_files": false, on the latest build

**Comment by C0D3D3V** [comment]
It would be very good if you test the old code, release [v1.7](https://github.com/C0D3D3V/Moodle-Downloader-2/releases/tag/v1.7), and if it works I know that the bug is in the new commits. If you have the time and desire, you can also test one commit after the other until it doesn't work anymore, but before that try to debug the code please:

 I'm really sorry, but this should be the easiest way. I think the program throws an exception that is not caught, but I do not know where. 

To debug the code do the following steps:

* Please install [Visual Studio Code](https://code.visualstudio.com/). 
* Then install the Extension `Python`, You have to press [CTRL + Shift + X] and then search for "Python" and install this extension. You will be asked to install some extra extensions in the notifications, you can accept these.
* Then you have to open the folder of the source code, you can do that in the menu under `files`-> `open folder`.

Then we can start debugging as described next:

Open the `main.py`file in the editor, then press  [CTRL + Shift + D] in the left widow go to the settings file by pressing the gear wheel or by clicking on "`create a launch.json file`". If you get asked what you want to launch select `python file`. The `launch.json` file should open, replace its content with that:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Moodle Downloader 2",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}\\main.py",
            "console": "integratedTerminal",
            "cwd": "C:\\Path\\where\\you\\want\\to\\test\\the\\downloader"
        }
    ]
}
```

Replace `C:\\Path\\where\\you\\want\\to\\test\\the\\downloader` with the path where you have your `config.json` file for testing.

Then start debugging by pressing [F5], you can then report me any errors.

**Comment by federicotorrielli** [comment]
Release 1.7 does work correctly for me, even in the debug.
I'm gonna test now the latest build.

**Comment by federicotorrielli** [comment]
What? Latest build works in the debug.
This is strange... did u make anything different in these hours?

**Comment by C0D3D3V** [comment]
Wow, thats great, I hope it works also without debugging. 

Yes I made some changes, a few related to this issue (I did not mark all as related to this issue), you can see them all here: https://github.com/C0D3D3V/Moodle-Downloader-2/commits/master

**Comment by federicotorrielli** [comment]
It does, even without debugging.
Thanks for the great work, dude!

**Comment by C0D3D3V** [comment]
I do it with pleasure :) You' re welcome!
