### ISSUE TITLE
Add support for Kaltura Extension

### ISSUE THREAD

**Issue by artaeun** [C0D3D3V/Moodle-Downloader-2#41]
The script does not download videos uploaded to kaltura with the kaltura moodle plugin: https://moodle.org/plugins/view.php?id=447

It just skips the video altogether. 

The videos are viewable from link:
MOODLESITE/mod/kalvidres/view.php?id=NUMERICID

**Comment by C0D3D3V** [comment]
Downloading the HTML files on which the videos are displayed should not be very difficult. 
Can you please try changing line 88 in `/moodle_connector/results_handler.py`? From:

     if (module_modname in ["resource", "folder", "url", "page"]):

to:

     if (module_modname in ["resource", "folder", "url", "page", "kalvidres"]):

To download the actual videos I have to think about more. I'll take a closer look at it after the exams.

**Comment by artaeun** [comment]
no html files are downloaded in the folder of the courses which have videos uploaded on moodle.

**Comment by C0D3D3V** [comment]
I tried to set up kaltura in my own Moodle, but that was not possible. Kaltura is completely commercial. So we need to sit down together again so I can gather more information.

**Comment by sononicola** [comment]
Hi
There is something I can do to help you to add this feature? In my university all video are uploaded in Kultura. I'm not a developer but if you tell me what links/xpaths you need I'll try to give you

**Comment by sononicola** [comment]
For downloding videos:
I'm in the page where the video is, then clicked with right click and opened only the video in a new tab (the firefox function), the in the console: [Imgur](https://imgur.com/IRSs4rz)
Opening the second link and right click and there is the "save video". 
Only thing is I don't know where the setting for video quality bitrate is. I remember some months ago it was there. @C0D3D3V

**Comment by C0D3D3V** [comment]
The problem is not the downloading of the videos itself. This should be relatively easy to implement. The real problem is that the downloader cannot get the data from the video. The link of the video would be important, but because Kaltura is not supported by the Moodle app, there is no easy way to get the link. 

I am already working on a solution. The Moodle Downloader-2 uses the Moodle API, so there is no easy way to get the link. However, I'm working on a way to generate a Moodle browser cookie that would allow you to access pages that are not supported by the API, and thus get the link for the Kultura video.

This is unnecessarily complicated and would be easier to implement if you didn't use the Moodle API. My old [Moodle downloader](https://github.com/C0D3D3V/Moodle-Downloader) does not have a maintainer, but it would be easier to implement there.

I'll share my progress here, probably I'll get a lot further today.

**Comment by C0D3D3V** [comment]
All Commits in the branch [issue-41](https://github.com/C0D3D3V/Moodle-Downloader-2/tree/issue-41) are related to this issue. I will only tag important commits (milestones) specifically to this issue.

**Comment by C0D3D3V** [comment]
It is now possible to generate the browser cookie. There is not much missing and hopefully it should be possible to download the videos soon.

**Comment by C0D3D3V** [comment]
I need your help now. Could one of you please download the latest version of the Issue-41 branch  (from here https://github.com/C0D3D3V/Moodle-Downloader-2/archive/issue-41.zip), preferably parallel to your current installation, so don't replace it, just copy your `config.json` and `moodle_state.db` to a new test folder... 

Then execute the main.py  with the `--log-responses` option. This creates a file called `responses.log` in the folder. You can stop the downloader with [Ctr+C] as soon as it starts downloading files (so as soon as the many percentage numbers are displayed), then nothing will change in the `responses.log` file. This file can contain private information, so it is best to send it to me by mail. 

I need this file so I know exactly what the JSON structure looks like.

**Comment by sononicola** [comment]
yeah sure. I'm having some trouble getting a new token (the old one expired).  In our moodle site doesn't work the automatic method and the moodle-app method (this because it launch a new page of our university login. In android works the app, but in the moodle Demo not). 

I remember last time I used the sso login with the console-method but for some reason this time there is not a moodlemobile://token=$apptoken in console.

Anyway: send me your mail address or telegram username to send the log

**Comment by C0D3D3V** [comment]
telegram username: c0d3d3v

**Comment by C0D3D3V** [comment]
We can also have a look at the soo process together, maybe we get an idea how to fix the token obtaining process.

**Comment by C0D3D3V** [comment]
Ok, we are ready for a test! Make sure you also set a `privatetoken` in the `config.json`, you can do this by running `python main.py --new-token --sso` or by doing it manually, the privatetoken is the part after the second `::::`. Set it in the config like this (don't forget the comma):

```
    "privatetoken": "8RpHJevJ42W7QN23OMkeYcdOYw3YfWgWGKsak7WB3Z88wcApSCVZ9TgY6M5fEO1m",
```

**Comment by C0D3D3V** [comment]
At this point this is now only a problem of Youtube-dl. Kaltura is basically supported by Youtube-dl (https://github.com/ytdl-org/youtube-dl/blob/master/docs/supportedsites.md) but not the Moodle plugin Kalvidre. If I have free time I can write a plugin for youtube-dl, so that it is supported too.

**Comment by k4j3d3v** [comment]
Hi, 
It would be very cool to support download of bbcollaborate video(lessons).
For now it doesn't seem to work, because where there are links to bbcollaborate recorded lesson it downloads related html pages.
Also an interesting thing is that it downloads together .desktop files with a public url for the videolectures.
So i solved the issue by making a very simple  script using the urls contained in these files.
But i think that to add direct support for that will not be so hard.

**Comment by C0D3D3V** [comment]
Yes we can try to implement that... Exactly for something like this I have prepared the architecture :D 
I just need more information, but more about that later. I'll get back to you in a week (as soon as I have time again). Then I'll ask again for the information I need.

**Comment by k4j3d3v** [comment]
Wonderful!
Let me know if i can do something meanwhile :)

**Comment by C0D3D3V** [comment]
I have been looking for a Moodle server for a long time where I can register and use Kaltura. I have only found the demo Kaltura Moodle page, but do not have login details. 

In order to write an extractor, I need access to a Moodle with Kaltura. Does anyone have a Moodle with Kaltura that you can log in to as an extern? Or does someone want to give me his tokens for 2 days?

**Comment by nsomaru** [comment]
Hi @C0D3D3V,

I'm interested in helping. Please clarify what you mean by "the source code for all the websites involved" and where you would like them to be sent?

Thanks.

**Comment by C0D3D3V** [comment]
very good, can we talk over Discord? My username is c0d3d3v#8812

I probably won't have time until Wednesday, but you can add me already. 

I can then guide you in a conversation so we can gather the necessary information together.

Have you already [installed vscode](https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Development-environment), that is not necessary, but then we could also directly make some tests if it works.

**Comment by C0D3D3V** [comment]
@nsomaru  I can also explain to you here what kind of information I need if you don't like to talk over Discord.

First, on your Moodle, open any Kaltura video so that in the URL  in the URL bar contains "/mod/kalvidres/view.php" . 
Then press [Ctrl + U] and send me the source code, which you can then see. You can send it to me by email or here.

**Comment by nsomaru** [comment]
sorry for the delay, was in an exam period. Have sent you the file over email (on your profile) as I didn't want to share the HTML publicly here.
