### ISSUE TITLE
[Feature Request] Download discussion forums

### ISSUE THREAD

**Issue by owlg** [C0D3D3V/Moodle-Downloader-2#50]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Is your feature request related to a problem? Please describe.

Discussion forums does not seem to be downloaded. Good to have grades downloaded too.
## Describe the solution you'd like

Archive discussion forums as well, possibly either using MarkDown or HTML.

**Comment by C0D3D3V** [comment]
Yeah great idea, I've wanted this function for ages. It just didn't have a high priority, because the mail notification is delayed but works quite well.
I have also written a wiki article about the API interface, in case someone wants to try it himself.
https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Moodle-API---Forums

Currently some other functions are in progress, until then this function has to wait.

**Comment by C0D3D3V** [comment]
I would be happy if someone implements it and makes a PullRequest. Due to my studies I will not be able to implement this in the near future.

**Comment by C0D3D3V** [comment]
I am finished the implementation. After a few tests it will be merged into master and will be in the next version.
