### ISSUE TITLE
How does Moodle Downloader affect the activity reports that instructors see?

### ISSUE THREAD

**Issue by Y-T-G** [C0D3D3V/Moodle-Downloader-2#66]
I was curious about how the [activity reports](https://docs.moodle.org/310/en/Activity_report) would appear for an instructor when I use the Moodle Downloader. Would they see me as having accessed the contents once Moodle Downloader downloads the content?

I am assuming that it would, since Moodle Downloader is using my credentials.

**Comment by C0D3D3V** [comment]
All interfaces used by the donwloader are listed here: https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Moodle-API

The activity reports contains mainly data triggered by a view event. View events are triggered by special interfaces which contain "_view", you can find them here:   https://docs.moodle.org/dev/Web_service_API_functions

That counts for pretty much everything, even the forum. So a teacher would not be able to tell that you downloaded the forum entries.

Otherwise the files are downloaded only once, so a normal behavior. That you downloaded a file can be traced of course.

Teachers can see the activity report for a course. However, most teachers will not even know how to open these logs.

 The activity report itself contains only general numbers, as "25 views by 6 users". So no relevant details. The log is more accurate.


If you run the downloader every 15 minutes, you won't even be able to see that you have viewed the course every 15 Minutes.


I add here one example: (The name of the student ist "Barbara Gardner") So she does not even appear in the logs:

I run the downloader 3 times, and downloaded these files:

```
+       History - Russia in Revolution/Welcome to the Course/Section summary.md
+       History - Russia in Revolution/Welcome to the Course/Listen to an outline of the 3 aims of the course h.md
+       History - Russia in Revolution/Useful resources/Section summary.md
+       History - Russia in Revolution/Useful resources/Russia in RevolutionIMPRESS.odp
+       History - Russia in Revolution/Useful resources/Long term causes of the Russian Revolution.md
+       History - Russia in Revolution/Useful resources/Russia in RevolutionPDF.pdf
+       History - Russia in Revolution/Welcome to the Course/Russian_Revolution_of_1917_PublicDomain.jpg
+       History - Russia in Revolution/Useful resources/VIDEO RESOURCE - An excellent video looking at the.md
+       History - Russia in Revolution/Useful resources/Materials to Read and Watch.md
+       History - Russia in Revolution/Collaborative Work/Class discussions/Class discussions.md
+       History - Russia in Revolution/Collaborative Work/Class discussions/20-04-24 Most important factor/[417] Anna Alexander.md
+       History - Russia in Revolution/Collaborative Work/Class discussions/20-04-24 Trip to St Petersburg!/[419] Jeffrey Sanders.md
+       History - Russia in Revolution/Collaborative Work/Class discussions/20-04-24 Trip to St Petersburg!/[420] Barbara Gardner response to [419].md
+       History - Russia in Revolution/Collaborative Work/Class discussions/20-04-24 Saving the revolution/[418] Jeffrey Sanders.md
+       History - Russia in Revolution/Collaborative Work/Revolution Glossary.md
+       History - Russia in Revolution/Collaborative Work/XML file of glossary entries.md
+       History - Russia in Revolution/Welcome to the Course/CourseAims.mp3
+       History - Russia in Revolution/Collaborative Work/Bolshevik Wiki.md
+       History - Russia in Revolution/Welcome to the Course/CourseAims_01.mp3
+       History - Russia in Revolution/Assessment/Mid-Module Assessment.md
+       History - Russia in Revolution/Assessment/Peer Assessment - Use of Source Materials.md
+       History - Russia in Revolution/Useful resources/Long term causes of the Russian Revolution.desktop
+       History - Russia in Revolution/Extra resources/Can you make a revolution.md
+       History - Russia in Revolution/Collaborative Work/Revolution Glossary.xml
+       History - Russia in Revolution/Assessment/Assignment - Causes of the October 1917 Revolution/submissions/Causes of 1917 Russian Revolution.pdf
+       History - Russia in Revolution/Useful resources/https -_www.youtube.com_watchv=tZPtipk03ZM
+       History - Russia in Revolution/Assessment/Assignment - Causes of the October 1917 Revolution/submissions/Causes of 1917 Russian Revolution.pdf


```
The Course:
![course_page](https://user-images.githubusercontent.com/14315968/100733232-2d3a3100-33ce-11eb-9f5c-8163f7778d30.png)


The activity Report before:
![activity_report_before](https://user-images.githubusercontent.com/14315968/100733269-3925f300-33ce-11eb-82f4-c9b8767ba166.png)

The Log before:
![log_before](https://user-images.githubusercontent.com/14315968/100733296-4216c480-33ce-11eb-9f56-8d0af0a8d8b9.png)



The activity report after:
![activity_report_after](https://user-images.githubusercontent.com/14315968/100733338-5064e080-33ce-11eb-8ae8-94b207438a85.png)

The Log after:
![log_after](https://user-images.githubusercontent.com/14315968/100733349-5490fe00-33ce-11eb-8436-1a4fcfbc82ab.png)



Finaly I navigated normaly on the webpage to force log entrys:


![foreced](https://user-images.githubusercontent.com/14315968/100733573-ad609680-33ce-11eb-99ce-9b79acc1b0e1.png)

**Comment by C0D3D3V** [comment]
Hope this answer your question

**Comment by Y-T-G** [comment]
Thank you very much for the detailed answer.
