### ISSUE TITLE
Downloading a course that is "public"/"allows guests" but in which I'm not enrolled

### ISSUE THREAD

**Issue by YassineElbouchaibi** [C0D3D3V/Moodle-Downloader-2#71]
## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

In my config I have :
```
"download_course_ids": [
        326
 ]
```
I added that course id manually. Moodle Downloader won't sync this course as I'm not enrolled in it even if the course is available publicly and anyone can download the files. I got the id via the web app :
![image](https://user-images.githubusercontent.com/46449697/104216627-4b9d3e80-5408-11eb-9084-31bae1862b9b.png)
 
Is this intended behaviour ? I have not looked at the code yet but could this be easily worked around ?

Note: I went through all the logs generated and even the responses and the course id never comes up.

## Steps to reproduce the issue

Try to download a course that is public but in which you are not enrolled.

## Expected behavior

If there is no permission error then the app should try to download the content from the requested course ids.

## Possible Fix

Not familiar with the code and the flow but we could, but I'm guessing do not filter out courses that in which the student is not enrolled.

**Comment by C0D3D3V** [comment]
This is somehow related to this very old request:  #6

So this is actually desired behaviour so far. But it is actually useful to be able to choose courses in which you are not enrolled. But it would be more useful if we create an extra array in the configuration, because if you use the integrated configurator the courses you are not enrolled in would be removed from the list.

As I explained in the old issue, for a hotfix you could just add your courses directly at this point: 
https://github.com/C0D3D3V/Moodle-Downloader-2/blob/c913368ca1efae4a4d8f8fdd217c42170059e774/moodle_dl/moodle_connector/moodle_service.py#L245

for e.g. like this:
```
courses = results_handler.fetch_courses(userid)
courses.append(Course(2342, 'course name', []))
```

The shorter course name that you can specify in the configuration will be overwritten at this point:
https://github.com/C0D3D3V/Moodle-Downloader-2/blob/c913368ca1efae4a4d8f8fdd217c42170059e774/moodle_dl/moodle_connector/moodle_service.py#L304

Currently I have a lot to do for the university, so if you feel like it you can try to implement something useful and create a PullRequest. Otherwise I will tackle this in a few days, should not be a big effort.

**Comment by YassineElbouchaibi** [comment]
I think I can give it a go, do you have a discord so I can ask you some questions in a more direct manner ?

**Comment by C0D3D3V** [comment]
c0d3d3v#8812 is my username in discord... if that does not work just send me a mail.

**Comment by YassineElbouchaibi** [comment]
I wasn't able to get you on discord so I'll just ask here. Do you know an endpoint that returns info about a course like its display name given the courseId ?

**Comment by YassineElbouchaibi** [comment]
Made a PR. Feel free to clone my PR and tweak it as you wish for formatting and naming of variables.

**Comment by C0D3D3V** [comment]
I have created a [wiki entry](https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Download-public-courses) for this option and linked it in the readme. Feel free to edit it. 

Thank you so much for implementing this in such a great way.
