### ISSUE TITLE
Add a Desktop GUI (maybe web app?)

### ISSUE THREAD

**Issue by tobiasfunke1** [C0D3D3V/Moodle-Downloader-2#89]
How about letting the whole tool run as a Django app?

Then we could view the courses in the browser and embed e.g. the videos and pdfs. 

Updating the courses would then be a management command.

**Comment by marzzzello** [comment]
What would be the advantage of that? You already have all the files downloaded and sorted into folders.

**Comment by tobiasfunke1** [comment]
I wouldn't have to search the folders for files but would have a proper **browsable** offline version of moodle. with course list, scrollable pages, embedded videos, etc.

**Comment by C0D3D3V** [comment]
The easiest way to get an offline Moodle is to use the offline feature of Moodle. The Moodle app, which is available for the most popular operating systems, already has the ability to display all Moodle content offline. 

Moodle-dl downloads not only all Moodle content but also external content. It would be a huge overhead to write an extra Django app for that. You could also just use a post script to feed another platform with the downloaded data. E.g. Nextcloud, Webdav or another learning platform (private Moodle?). In any case I would say this would be something for an extra repo, because it doesn't really need to rely on any internal functionality of moodle-dl, everything that is needed can be solved by integrating moodle-dl.

**Comment by C0D3D3V** [comment]
But of course I don't want to stop you, if you have a big desire to write a django app and you need more functionality, e.g. callbacks that inform about new files, this can of course be integrated.

**Comment by Megver83** [comment]
We use Moodle at my university, like many others. Many (most?) of these Moodle users have no idea of how to use CLI and/or Python. A browsable GUI would be more portable, and maybe easier, than using a GUI toolkit. The advantage of having a GUI is that much more people with less technical knowledge would be able to take advantage of this great software. This is kinda the same idea that of what Syncthing does.

**Comment by C0D3D3V** [comment]
@Megver83 So you would also prefer a web GUI instead of a normal window-based GUI?

**Comment by Megver83** [comment]
I knew syncthing-gtk. Honestly, idk what are the advantages of a web GUI vs typical window GUI. IMHO, the easiest implementation should be done, but I'm OK with any of the two.

**Comment by C0D3D3V** [comment]
I like the idea of a Django app for moodle-dl more and more, I think this could be a long term goal.

**Comment by C0D3D3V** [comment]
After reading more and more into the matter I think it would be easiest and best to just build a QT app using PySide6.

To build a web app to view the downloaded files I think is completely out of the question, for this you can simply use an OwnCloud for example. 

 I think a desktop app to make all the settings is much more useful. The complete CLI configurator could be replaced by a practical GUI. In the same course you can use an integrated WebView to obtain the SSO token comfortably.
